# ==========================
# Elasticsearch StatefulSet
# ==========================
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elasticsearch
  namespace: logging
spec:
  serviceName: elasticsearch
  replicas: {{ .Values.elasticsearch.replicas }}
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      securityContext:
        fsGroup: {{ .Values.elasticsearch.securityContext.fsGroup }}
      containers:
        - name: elasticsearch
          securityContext:
            runAsUser: {{ .Values.elasticsearch.securityContext.runAsUser }}
          image: docker.elastic.co/elasticsearch/elasticsearch:8.10.2
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 9200
          env:
            - name: discovery.type
              value: single-node
            - name: ES_JAVA_OPTS
              value: "-Xms1g -Xmx1g"
            - name: ES_LOG_STYLE
              value: file
          resources:
            requests:
              cpu: 500m
              memory: 2Gi
            limits:
              cpu: 1
              memory: 4Gi
          volumeMounts:
            - name: elastic-data
              mountPath: /usr/share/elasticsearch/data
            - name: elastic-tmp
              mountPath: /tmp
      volumes:
        - name: elastic-tmp
          emptyDir: {}
  volumeClaimTemplates:
    - metadata:
        name: elastic-data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: managed-csi   # Uses Azure Managed Disk
        resources:
          requests:
            storage: 50Gi
---
# =====================
# Elasticsearch Service
# =====================
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: logging
  labels:
    app: elasticsearch
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 9200
      targetPort: 9200
  selector:
    app: elasticsearch
