apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-config
  namespace: logging
data:
  logstash.conf: |
    input {
       tcp {
        port => 5044
        codec => json
      }
    }

    filter {
      json {
        source => "message"
      }
    }

    output {
      elasticsearch {
        hosts => ["http://elasticsearch:9200"]
        index => "widgetario-logs-%{+YYYY.MM.dd}"
      }
      stdout { codec => rubydebug }
    }
