apiVersion: apps/v1
kind: Deployment
metadata:
  name: logstash
spec:
  replicas: {{ .Values.logstash.replicas }}
  selector:
    matchLabels:
      app: logstash
  template:
    metadata:
      labels:
        app: logstash
    spec:
      containers:
        - name: logstash
          image: {{ .Values.logstash.image }}
          volumeMounts:
            - name: logstash-config
              mountPath: /usr/share/logstash/pipeline
            - name: widgetario-logs
              mountPath: /var/log/widgetario
          ports:
            - containerPort: 5044
      volumes:
        - name: logstash-config
          configMap:
            name: logstash-config
        - name: widgetario-logs
          hostPath:
            path: /var/log/pods/widgetario
            type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: logstash
spec:
  ports:
    - port: 5044
      targetPort: 5044
  selector:
    app: logstash
