apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.grafanaReplicas }}
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
        - name: grafana
          image: {{ .Values.grafanaImage }}
          env:
            - name: GF_SECURITY_ADMIN_USER
              value: {{ .Values.grafanaAdminUser }}
            - name: GF_SECURITY_ADMIN_PASSWORD
              value: {{ .Values.grafanaAdminPassword }}
          ports:
            - containerPort: {{ .Values.grafanaPort }}
          volumeMounts:
            - name: grafana-config
              mountPath: /etc/grafana/provisioning/datasources
            - name: grafana-storage
              mountPath: /var/lib/grafana
      volumes:
        - name: grafana-config
          configMap:
            name: grafana-config
        - name: grafana-storage
          emptyDir: {}
