{{- if .Values.grafana.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: grafana
  namespace: {{ .Values.namespace }}
  annotations:
{{- range $key, $value := .Values.grafana.ingress.annotations }}
    {{ $key }}: "{{ $value }}"
{{- end }}
spec:
  ingressClassName: {{ .Values.grafana.ingress.className }}
  rules:
    - host: {{ .Values.grafana.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: grafana
                port:
                  number: {{ .Values.grafana.service.port }}
  {{- if .Values.grafana.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.grafana.ingress.host }}
      secretName: {{ .Values.grafana.ingress.tls.secretName }}
  {{- end }}
{{- end }}
