apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  selector:
    app: grafana
  ports:
    - name: http
      port: {{ .Values.grafanaPort }}
      targetPort: {{ .Values.grafanaPort }}
