apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  selector:
    app: prometheus
  ports:
    - name: http
      port: {{ .Values.prometheusPort }}
      targetPort: {{ .Values.prometheusPort }}
