apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prometheus
  namespace: {{ .Values.namespace }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: {{ .Values.ingressClassName }}
  rules:
    - host: prometheus.{{ .Values.domainName }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: prometheus
                port:
                  number: {{ .Values.prometheusPort }}
{{- if .Values.enableTLS }}
  tls:
    - hosts:
        - prometheus.{{ .Values.domainName }}
      secretName: {{ .Values.tlsSecretName }}
{{- end }}
