apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: {{ .Values.namespace }}
data:
  prometheus.yml: |-
    global:
      scrape_interval: 30s
    scrape_configs:
      - job_name: 'app'
        kubernetes_sd_configs:
        - role: pod 
        relabel_configs:
        - source_labels: 
            - __meta_kubernetes_namespace
          action: keep
          regex: default
        - source_labels: 
            - __meta_kubernetes_pod_annotationpresent_prometheus_io_scrape
            - __meta_kubernetes_pod_annotation_prometheus_io_scrape
          regex: true;true
          action: keep
        - source_labels: 
            - __meta_kubernetes_pod_name
          target_label: instance
